version: '3'
services:
  php:
    image: php:8.1.24-cli
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - composer

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: ["install"]
